### ISSUE TITLE
Decide on rules for naming Actions

### ISSUE THREAD

**Issue by joshfarrant** [joshfarrant/shortcuts-js#26]
CONTRIBUTING.md currently states

> The file (and action) you're creating should be the name of the action as it appears in the Shortcuts app, camelCased.

This works fine for the majority of actions, however it's not perfect when naming actions with upper case words in the name, eg `SSH` and `URL`.

We might want to consider tweaking the rule to allow for action names to keep upper-case strings as upper-case. The table below shows some examples of this.

Action Name | Proposed | Current
--- | --- | ---
Get Contents of URL | `getContentsOfURL` | `getContentsOfUrl`
Get Current IP Address | `getCurrentIPAddress` | `getCurrentIPAddress`
Run Script Over SSH | `runScriptOverSSH` | `runScriptOverSSH`
URL | `URL` | `url`

@xAlien95 has [pointed out](https://github.com/joshfarrant/shortcuts-js/pull/8#discussion_r235121730):

> It's in line with standard JavaScript functions/properties such as innerHTML

Does anyone foresee any issues with one solution over the other? If not, I'll probably go with the proposed change.

**Comment by xAlien95** [comment]
@joshfarrant, since #47 has been merged, now all the action function names can be replaced with the proposed ones. In that pull request I added PascalCased variable name validation in `tslint.json` (that was required for the private `Variable` class).

**Comment by joshfarrant** [comment]
@xAlien95 I spotted that in your PR and was wondering if it would do the trick. I'm happy with that then, I'll go through and make the adjustments now.

**Comment by joshfarrant** [comment]
The naming of `showInItunesStore` still makes me kind of sad to look at. Would `showInITunesStore` be better? And if so should `runJavascriptOnWebPage` be `runJavaScriptOnWebPage`?

**Comment by xAlien95** [comment]
> The naming of showInItunesStore still makes me kind of sad to look at. Would showInITunesStore be better?

`showInITunesStore` looks better.

> And if so should runJavascriptOnWebPage be runJavaScriptOnWebPage?

The original shown name is "Run JavaScript on Web Page" if I recall correctly, so `runJavaScriptOnWebPage` should be the right one.

**Comment by joshfarrant** [comment]
Cool, I’ll adjust those too then.
