### ISSUE TITLE
Is it possible to port the "shortcuts" app to Android？ Parsing the file format and Implement the action.

### ISSUE THREAD

**Issue by jane00** [joshfarrant/shortcuts-js#286]
There is NO app on Android can do this.

And there are already many useful .shortcut very useful.

**Comment by joshfarrant** [comment]
I'm afraid it's unlikely. In theory someone could create an app for Android which accepts and parses .shortcut files, then maps the functionality onto Android system functions, but I can't see anyone doing that if I'm honest.
