### ISSUE TITLE
Find a way to track Actions to be implemented

### ISSUE THREAD

**Issue by joshfarrant** [joshfarrant/shortcuts-js#3]
Up to this point I've just picked actions almost at random and implemented them. It would be nice to have a more structured way of tracking actions which are yet to be implemented.

Is there a nicer way to do this than just having a huge checklist the README or an issue?

**Comment by joshstrange** [comment]
This problem gets bigger when you consider 3rd party apps that provide shortcuts. Maybe a folder inside of the actions folder for each app id (and use com.apple.comething) for all the base iOS actions. Then add a readme to each folder that you can put a checklist in. That way people can easier add to the checklist (without necessarily adding the code to support the action) and other people (or the submitter) can work from the checklist to implement the actions.

**Comment by joshfarrant** [comment]
That sounds like a nice way to handle it. I might add a couple of example 3rd party app directories to see what this could look like.

**Comment by ThomasDeLange** [comment]
Maybe a GitHub project? Where you can drag an drop from to do -> in progress -> done

**Comment by joshfarrant** [comment]
@ThomasDeLange Are you thinking about a Kanban board sort of layout and, if so, does GitHub support that? I know GitLab has a 'board' view for its issues which essentially does what you've described.

The in progress step might not be necessary too, as it could often be difficult to know when something is in progress. Also, new actions will probably only take ~15 minutes to be implemented, so they won't be in progress for very long.

**Comment by joshfarrant** [comment]
I've opened #6 for now, as it's useful to at least have a place to track this for now. We'll see how that goes for just the default actions.

**Comment by ThomasDeLange** [comment]
@joshfarrant Yes, indeed something like a Kaban board. Next to pull requests you can go to projects and add a project. For example one for actions and a few for big third-party apps. Everything in done is included and everything in to do has yet to be implemented.

**Comment by ThomasDeLange** [comment]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/33953384/48777094-f3f46400-ecd1-11e8-814a-87849af21301.png">
@joshfarrant something like this? You can even automate it with issues mabye that's to much😂

**Comment by joshfarrant** [comment]
Oh cool, TIL! I'll have a look into this, thanks @ThomasDeLange.

**Comment by joshfarrant** [comment]
I'm going to close this, as #6 is working quite well at the moment.
