### ISSUE TITLE
Speak Text

### ISSUE THREAD

**Issue by n33kos** [joshfarrant/shortcuts-js#308]
- [ ] These actions aren't already listed in the 'All Actions to be implemented' issue [here](https://github.com/joshfarrant/shortcuts-js/issues/6).
- [x] These actions haven't already been requested in another issue.
- [x] Fill out the information below, deleting the examples in italics.

**What is the name of the app these actions are a part of?**
_Shortcuts_

**Is this a free or paid app?**
_Free_

**Please list all of the actions this app exposes.**
- _Speak Text_

**Provide a link to download a .shortcut file containing as many of these actions as possible.**
_[iCloud](https://www.icloud.com/shortcuts/fa4e4278164649a38bdb1cdf64fb6fb6)_

**Comment by n33kos** [comment]
I'm working on implementing `speakText` and the docs said to bring it up in conversation here first. I'll have a PR up fairly soon, still need to see if I can find definitions for a few types it uses.

**Comment by n33kos** [comment]
https://github.com/joshfarrant/shortcuts-js/pull/311

**Comment by joshfarrant** [comment]
Merged and published!
