### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by scrutinizer11** [joshfarrant/shortcuts-js#592]
I unzipped the archive. Now what? How do I compile it? **Readme** just contains code examples without specifying what to do with the contents. Usually, you compile and install. How's it different in this case?

**Comment by joshfarrant** [comment]
Hi @scrutinizer11, this is a JavaScript library and can only be interacted with using JavaScript. Typically you'd install it from npm then import/require shortcuts-js from within your code base.

Unless you're writing JS you'll struggle to use the library.
